<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\RolesController.cs" />
    <Compile Remove="Controllers\UsersController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
	  <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.6.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogixSys.AuthServer.Application\LogixSys.AuthServer.Application.csproj" />
    <ProjectReference Include="..\LogixSys.AuthServer.Contracts\LogixSys.AuthServer.Contracts.csproj" />
    <ProjectReference Include="..\LogixSys.AuthServer.Infrastructure\LogixSys.AuthServer.Infrastructure.csproj" />
    <ProjectReference Include="..\LogixSys.AuthServer.Persistence\LogixSys.AuthServer.Persistence.csproj" />
  </ItemGroup>

</Project>
